# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameZone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.3'
  pod 'DropDown'

  # Pods for GameZone

  target 'GameZoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameZoneUITests' do
    # Pods for testing
  end

end
